# This is a basic workflow to help you get started with Actions

name: Add Label to opened Issues

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [ opened ] 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  addLabelToIssue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: RegEx Issue Labeler
      uses: github/issue-labeler@v2.0
      with:
        # The GITHUB_TOKEN secret
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        # Path to the labeler.yml configuration file
        configuration-path: .github/config/labelerRules.yml
