name: Notify users based on issue labels v2

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: jenschelkopf/issue-label-notification-action@1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          recipients: |
            'area: exchange'=@kenkilty
            'area: sharepoint'=@briantjackett
            'area: teams'=@briantjackett
