name: Add Label to opened Issues

on:
  issues:
    types: [ opened ] 

jobs:
  addLabelToIssue:
    runs-on: ubuntu-latest

    steps:
    - name: Auto label
      uses: Renato66/auto-label@v2.1.2
      with:
        # github token for the repository
        repo-token:  "${{ secrets.Issue_Notifier_PAT }}"
        # 
        ignore-comments: true
        # 
        labels-synonyms: '{"area: sharepoint":["Product: sharepoint"],"area: exchange":["Product: exchange"]}'
        # 
        labels-not-allowed: '["good first issue"]'
        # 
        #default-labels: ''
